ifeq ($(OS),Windows_NT)
	CC = x86_64-w64-mingw32-gcc
else
	CC = clang
endif

CFLAGS = -Wall -Wextra -Werror -std=c99 -nostdlib -ffreestanding -O3 -pedantic -ffp-contract=off

# Unfortunately, I have found that make quite often selects the wrong shell
# (e.g. PowerShell), so commands like "find" won't work unless we explicitly
# specify bash.  You also can't use a variable for this (e.g. $(SHELL)) as make
# inexplicably tries to read something from the PATH and fails.  So hardcoding a
# reference to bash seems to be the only way to get a working build.
C_FILES = $(shell bash -c "find src -type f -iname ""*.c""")
H_FILES = $(shell bash -c "find src -type f -iname ""*.h""")
O_FILES = $(patsubst src/%.c,obj/%.o,$(C_FILES))
TOTAL_REBUILD_FILES = makefile $(H_FILES)

TESTS = $(patsubst tests/%, %, $(shell bash -c "find tests -mindepth 1 -maxdepth 1 -type d"))

dist/mod_to_c: $(O_FILES)
	mkdir -p $(dir $@)
	$(CC) $(CLAGS) -flto $(O_FILES) -o $@

obj/%.o: src/%.c $(TOTAL_REBUILD_FILES)
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

test: $(patsubst %, tests/%/pass, $(TESTS))

tests/%/actual.c: tests/%/input.mod dist/mod_to_c
	mkdir -p $(dir $@)
	dist/mod_to_c example_song_name SONG_MACRO_NAME SONG_NAME_MACRO_NAME INSTRUMENT_LIST_MACRO_NAME INSTRUMENT_MACRO_NAME INSTRUMENT_INDEX_MACRO_NAME FINE_TUNING_MACRO_NAME VOLUME_MACRO_NAME INSTRUMENT_REPEAT_POINT_MACRO_NAME INSTRUMENT_SAMPLE_LIST_MACRO_NAME INSTRUMENT_SAMPLE_MACRO_NAME PATTERN_LIST_MACRO_NAME PATTERN_MACRO_NAME PATTERN_INDEX_MACRO_NAME PLAYLIST_INDEX_MACRO_NAME PATTERN_LINE_LIST_MACRO_NAME PATTERN_LINE_MACRO_NAME LINE_INDEX_MACRO_NAME PATTERN_LINE_CHANNEL_LIST_MACRO_NAME PATTERN_LINE_CHANNEL_MACRO_NAME CHANNEL_INDEX_MACRO_NAME PERIOD_NOT_SPECIFIED_MACRO_NAME PERIOD_SPECIFIED_MACRO_NAME INSTRUMENT_NOT_SPECIFIED_MACRO_NAME INSTRUMENT_SPECIFIED_MACRO_NAME NO_EFFECT_MACRO_NAME ARPEGGIO_EFFECT_MACRO_NAME SEMITONES_MACRO_NAME PATTERN_BREAK_EFFECT_MACRO_NAME POSITION_JUMP_EFFECT_MACRO_NAME COARSE_PORTAMENTO_EFFECT_MACRO_NAME TONE_PORTAMENTO_EFFECT_MACRO_NAME VIBRATO_EFFECT_MACRO_NAME TREMOLO_EFFECT_MACRO_NAME FINE_PAN_EFFECT_MACRO_NAME SAMPLE_OFFSET_EFFECT_MACRO_NAME VOLUME_SLIDE_EFFECT_MACRO_NAME VOLUME_SLIDE_TONE_PORTAMENTO_EFFECT_MACRO_NAME VOLUME_SLIDE_VIBRATO_EFFECT_MACRO_NAME VOLUME_EFFECT_MACRO_NAME COARSE_PAN_EFFECT_MACRO_NAME ENABLE_FILTER_EFFECT_MACRO_NAME DISABLE_FILTER_EFFECT_MACRO_NAME FINE_PORTAMENTO_EFFECT_MACRO_NAME ENABLE_GLISSANDO_EFFECT_MACRO_NAME DISABLE_GLISSANDO_EFFECT_MACRO_NAME RETRIGGERING_SINE_VIBRATO_EFFECT_MACRO_NAME RETRIGGERING_SAWTOOTH_VIBRATO_EFFECT_MACRO_NAME RETRIGGERING_SQUARE_VIBRATO_EFFECT_MACRO_NAME RETRIGGERING_RANDOM_VIBRATO_EFFECT_MACRO_NAME CONTINUOUS_SINE_VIBRATO_EFFECT_MACRO_NAME CONTINUOUS_SAWTOOTH_VIBRATO_EFFECT_MACRO_NAME CONTINUOUS_SQUARE_VIBRATO_EFFECT_MACRO_NAME CONTINUOUS_RANDOM_VIBRATO_EFFECT_MACRO_NAME RETRIGGERING_SINE_TREMOLO_EFFECT_MACRO_NAME RETRIGGERING_SAWTOOTH_TREMOLO_EFFECT_MACRO_NAME RETRIGGERING_SQUARE_TREMOLO_EFFECT_MACRO_NAME RETRIGGERING_RANDOM_TREMOLO_EFFECT_MACRO_NAME CONTINUOUS_SINE_TREMOLO_EFFECT_MACRO_NAME CONTINUOUS_SAWTOOTH_TREMOLO_EFFECT_MACRO_NAME CONTINUOUS_SQUARE_TREMOLO_EFFECT_MACRO_NAME CONTINUOUS_RANDOM_TREMOLO_EFFECT_MACRO_NAME FINE_VOLUME_SLIDE_EFFECT_MACRO_NAME NOTE_CUT_EFFECT_MACRO_NAME NOTE_DELAY_EFFECT_MACRO_NAME PATTERN_DELAY_EFFECT_MACRO_NAME INVERT_LOOP_EFFECT_MACRO_NAME CANCEL_INVERT_LOOP_EFFECT_MACRO_NAME SPEED_EFFECT_MACRO_NAME PERIODS_PER_TICK_MACRO_NAME PERIODS_MACRO_NAME SIXTY_FOURTH_LOOPS_PER_TICK_MACRO_NAME FINE_PANNING_MACRO_NAME COARSE_PANNING_MACRO_NAME SAMPLE_INDEX_MACRO_NAME VOLUME_PER_TICK_MACRO_NAME VOLUMES_MACRO_NAME PERIOD_MACRO_NAME TICKS_MACRO_NAME REPEATS_MACRO_NAME DELAY_TICKS_MACRO_NAME CONFIGURE_PATTERN_LOOP_EFFECT_MACRO_NAME START_PATTERN_LOOP_EFFECT_MACRO_NAME RETRIGGER_EFFECT_MACRO_NAME FINE_TUNE_EFFECT_MACRO_NAME PLAYLIST_MACRO_NAME test/include/a.h test/include/b.h test/include/c.h < $< > $@

tests/%/pass: tests/%/expected.c tests/%/actual.c
	diff $^
	mkdir -p $(dir $@)
	touch $@

clean:
	rm -rf obj dist $(patsubst %, tests/%/pass, $(TESTS))
