ifeq ($(OS),Windows_NT)
	CC = x86_64-w64-mingw32-gcc
else
	CC = clang
endif

CFLAGS = -Wall -Wextra -Werror -std=c99 -nostdlib -ffreestanding -O3 -pedantic -ffp-contract=off

# Unfortunately, I have found that make quite often selects the wrong shell
# (e.g. PowerShell), so commands like "find" won't work unless we explicitly
# specify bash.  You also can't use a variable for this (e.g. $(SHELL)) as make
# inexplicably tries to read something from the PATH and fails.  So hardcoding a
# reference to bash seems to be the only way to get a working build.
C_FILES = $(shell bash -c "find src -type f -iname ""*.c""")
H_FILES = $(shell bash -c "find src -type f -iname ""*.h""")
O_FILES = $(patsubst src/%.c,obj/%.o,$(C_FILES))
TOTAL_REBUILD_FILES = makefile $(H_FILES)

TESTS = $(patsubst tests/%, %, $(shell bash -c "find tests -mindepth 1 -maxdepth 1 -type d"))

dist/mod_to_c: $(O_FILES)
	mkdir -p $(dir $@)
	$(CC) $(CLAGS) -flto $(O_FILES) -o $@

obj/%.o: src/%.c $(TOTAL_REBUILD_FILES)
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

test: $(patsubst %, tests/%/pass, $(TESTS))

tests/%/actual.c: tests/%/input.mod dist/mod_to_c
	mkdir -p $(dir $@)
	dist/mod_to_c test_song_name TEST_INSTRUMENT_INDEX_MACRO_NAME TEST_FINE_TUNING_MACRO_NAME TEST_VOLUME_MACRO_NAME TEST_SAMPLE_INDEX_MACRO_NAME TEST_SAMPLE_LIST_MACRO_NAME TEST_SAMPLE_MACRO_NAME TEST_NON_LOOPING_INSTRUMENT_MACRO_NAME TEST_FULLY_LOOPING_INSTRUMENT_MACRO_NAME TEST_PARTIALLY_LOOPING_INSTRUMENT_MACRO_NAME TEST_STATE_INDEX_MACRO_NAME TEST_STATE_COMMAND_LIST_MACRO_NAME TEST_STATE_MACRO_NAME TEST_CHANNEL_INDEX_MACRO_NAME TEST_SEMITONE_MACRO_NAME TEST_UNIT_MACRO_NAME TEST_TICK_MACRO_NAME TEST_ARPEGGIO_COMMAND_MACRO_NAME TEST_COARSE_PORTAMENTO_UP_COMMAND_MACRO_NAME TEST_COARSE_PORTAMENTO_DOWN_COMMAND_MACRO_NAME TEST_TONE_PORTAMENTO_COMMAND_MACRO_NAME TEST_RESTARTING_SINUSOIDAL_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_SAWTOOTH_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_SQUARE_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_RANDOM_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SINUSOIDAL_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SAWTOOTH_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SQUARE_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_RANDOM_VIBRATO_OSCILLATOR_COMMAND_MACRO_NAME TEST_VIBRATO_SPEED_COMMAND_MACRO_NAME TEST_VIBRATO_DEPTH_COMMAND_MACRO_NAME TEST_VIBRATO_COMMAND_MACRO_NAME TEST_RESTARTING_SINUSOIDAL_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_SAWTOOTH_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_SQUARE_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_RESTARTING_RANDOM_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SINUSOIDAL_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SAWTOOTH_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_SQUARE_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_CONTINUING_RANDOM_TREMOLO_OSCILLATOR_COMMAND_MACRO_NAME TEST_TREMOLO_SPEED_COMMAND_MACRO_NAME TEST_TREMOLO_DEPTH_COMMAND_MACRO_NAME TEST_TREMOLO_COMMAND_MACRO_NAME TEST_FINE_PAN_COMMAND_MACRO_NAME TEST_COARSE_PAN_COMMAND_MACRO_NAME TEST_SAMPLE_OFFSET_COMMAND_MACRO_NAME TEST_VOLUME_SLIDE_COMMAND_MACRO_NAME TEST_VOLUME_COMMAND_MACRO_NAME TEST_ENABLE_FILTER_COMMAND_MACRO_NAME TEST_DISABLE_FILTER_COMMAND_MACRO_NAME TEST_FINE_PORTAMENTO_UP_COMMAND_MACRO_NAME TEST_FINE_PORTAMENTO_DOWN_COMMAND_MACRO_NAME TEST_ENABLE_GLISSANDO_COMMAND_MACRO_NAME TEST_DISABLE_GLISSANDO_COMMAND_MACRO_NAME TEST_NOTE_COMMAND_MACRO_NAME TEST_RETRIGGER_COMMAND_MACRO_NAME TEST_NOTE_CUT_COMMAND_MACRO_NAME TEST_NOTE_DELAY_COMMAND_MACRO_NAME TEST_INVERT_LOOP_COMMAND_MACRO_NAME TEST_REVERT_INVERT_LOOP_COMMAND_MACRO_NAME TEST_SET_SPEED_TEMPO_MACRO_NAME TEST_SONG_MACRO_NAME test/include/a.h test/include/b.h test/include/c.h < $< > $@

tests/%/pass: tests/%/expected.c tests/%/actual.c
	diff $^
	mkdir -p $(dir $@)
	touch $@

clean:
	rm -rf obj dist $(patsubst %, tests/%/pass, $(TESTS))
